name: video-auto-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
    - ffmpeg-python==0.2.0
    - faster-whisper==0.10.0
    - flask==3.0.0
    - pytest==7.4.3
    - pytest-cov==4.1.0
