name: video-auto-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - mlx
  - pytest
  - pytest-cov
  - beautifulsoup4
  - pip:
    - "numpy<2"
    - ffmpeg-python
    - flask
    - anthropic
    - faster-whisper
    - insanely-fast-whisper
