name: video-auto-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchaudio
    - numpy<2.0
    - ffmpeg-python
    - flask
    - transformers>=4.35.0
    - optimum>=1.13.2
    - accelerate>=0.24.1
    - rich>=13.7.0
    - setuptools>=68.2.2
    - anthropic
