name: video-auto-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - "insanely-fast-whisper @ git+https://github.com/Vaibhavs10/insanely-fast-whisper"  # Install from git to bypass Python version check
    - -e .[dev]  # Install package in editable mode with dev dependencies
